config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :boards
  resources :comments
  resources :discussions
  resources :user_forms
  devise_for :users
  resources :vaccinations
  root to: 'pages#home'

  get 'pages/index'
  get 'pages/tictac'

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :discussion

  validates :content, presence: true, length: { minimum: 2, maximum: 250 }

  after_create_commit { CommentBroadcastJob.perform_later(self) }
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy

  validates_presence_of :title, :body
end

app/models/form_image.rb
class FormImage < ApplicationRecord
  belongs_to :user_form

  mount_uploader :main_image, FormImageUploader
end

app/models/guest_user.rb
class GuestUser < User 
  attr_accessor :name, :email, :first_name, :last_name, :id
end

app/models/player.rb
class Player < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :editor], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name

  has_many :user_forms, dependent: :destroy
  has_many :discussions, dependent: :destroy
  has_many :comments, dependent: :destroy

  def first_name
    self.name.split.first 
  end

  def last_name
    self.name.split.last 
  end
end

app/models/user_form.rb
class UserForm < ApplicationRecord
  belongs_to :user
  has_many :form_images
  has_many :vaccs

  accepts_nested_attributes_for :vaccs,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['rec'].blank? }

  accepts_nested_attributes_for :form_images,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['main_image'].blank? }
end

app/models/vacc.rb
class Vacc < ApplicationRecord
  belongs_to :user_form

  validates_presence_of :title
end

app/models/vaccination.rb
class Vaccination < ApplicationRecord
  validates_presence_of :title
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def index
  end

  def tictac

  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
end

app/controllers/vaccinations_controller.rb
class VaccinationsController < ApplicationController
  before_action :set_vaccination, only: [:show, :edit, :update, :destroy]

  # GET /vaccinations
  # GET /vaccinations.json
  def index
    @vaccinations = Vaccination.all
  end

  # GET /vaccinations/1
  # GET /vaccinations/1.json
  def show
  end

  # GET /vaccinations/new
  def new
    @vaccination = Vaccination.new
  end

  # GET /vaccinations/1/edit
  def edit
  end

  # POST /vaccinations
  # POST /vaccinations.json
  def create
    @vaccination = Vaccination.new(vaccination_params)

    respond_to do |format|
      if @vaccination.save
        format.html { redirect_to @vaccination, notice: 'Vaccination was successfully created.' }
        format.json { render :show, status: :created, location: @vaccination }
      else
        format.html { render :new }
        format.json { render json: @vaccination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vaccinations/1
  # PATCH/PUT /vaccinations/1.json
  def update
    respond_to do |format|
      if @vaccination.update(vaccination_params)
        format.html { redirect_to @vaccination, notice: 'Vaccination was successfully updated.' }
        format.json { render :show, status: :ok, location: @vaccination }
      else
        format.html { render :edit }
        format.json { render json: @vaccination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vaccinations/1
  # DELETE /vaccinations/1.json
  def destroy
    @vaccination.destroy
    respond_to do |format|
      format.html { redirect_to vaccinations_url, notice: 'Vaccination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vaccination
      @vaccination = Vaccination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vaccination_params
      params.require(:vaccination).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
  def gravatar_helper user
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 50
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/user_forms_helper.rb
module UserFormsHelper
  def image_generator(height:, width:)
    "http://via.placeholder.com/#{height}x#{width}"
  end

  def form_img img, type
    if img.model.main_image? 
      img
    elsif type == 'main'
      image_generator(height: '600', width: '400')
    end
  end
end

app/helpers/vaccinations_helper.rb
module VaccinationsHelper
end

app/views/vaccinations/_form.html.erb
<div class="row">
  <div class="col-sm-5">
    <%= form_with(model: vaccination, local: true) do |form| %>
      <% if vaccination.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(vaccination.errors.count, "error") %> prohibited this vaccination from being saved:</h2>

          <ul>
          <% vaccination.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, id: :vaccination_title, class: 'form-control' %>
      </div>

      <div class="form-group mid-marg">
        <%= form.submit 'Create Vaccination', class: 'btn btn-outline-success btn-block' %>
      </div>
    <% end %>
  </div>
</div>

app/views/vaccinations/edit.html.erb
<div class="container large-marg">
  <h1 class="mid-marg">Edit Vaccination</h1>

  <%= render 'form', vaccination: @vaccination %>

  <div class="large-marg">
    <%= link_to 'Show', @vaccination, class: 'btn' %> |
    <%= link_to 'Back', vaccinations_path, class: 'btn' %>
  </div>
</div>

app/views/vaccinations/index.html.erb
<div class="container">

  <h1 class="mid-marg">Vaccinations</h1>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @vaccinations.each do |vaccination| %>
        <tr>
          <td><%= vaccination.title %></td>
          <td><%= link_to 'Show', vaccination %></td>
          <td><%= link_to 'Edit', edit_vaccination_path(vaccination) %></td>
          <td><%= link_to 'Destroy', vaccination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <div class="mid-marg">
    <%= link_to 'New Vaccination', new_vaccination_path, class: 'btn btn-outline-info' %>
  </div>
</div>

app/views/vaccinations/new.html.erb
<div class="container large-marg">
  <h1 class="mid-marg">New Vaccination</h1>

  <%= render 'form', vaccination: @vaccination %>

  <div class="large-marg">
    <%= link_to 'Back', vaccinations_path, class: 'btn btn-outline-secondary' %>
  </div>
</div>

app/views/vaccinations/show.html.erb
<div class="container">
  <div class="large-marg text-center">
    <h1 class="mid-marg padd">
      <%= @vaccination.title %>
    </h1>
  </div>

  <div class='mid-marg'>
    <%= link_to 'Edit', edit_vaccination_path(@vaccination), class: 'btn btn-outline-dark' %> |
    <%= link_to 'Back', vaccinations_path, class: 'btn btn-outline-dark' %>
  </div>
</div>