config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :boards
  resources :comments
  resources :discussions
  resources :user_forms
  devise_for :users
  resources :vaccinations
  root to: 'pages#home'

  get 'pages/index'
  get 'pages/tictac'

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :discussion

  validates :content, presence: true, length: { minimum: 2, maximum: 250 }

  after_create_commit { CommentBroadcastJob.perform_later(self) }
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy

  validates_presence_of :title, :body
end

app/models/form_image.rb
class FormImage < ApplicationRecord
  belongs_to :user_form

  mount_uploader :main_image, FormImageUploader
end

app/models/guest_user.rb
class GuestUser < User 
  attr_accessor :name, :email, :first_name, :last_name, :id
end

app/models/player.rb
class Player < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :editor], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name

  has_many :user_forms, dependent: :destroy
  has_many :discussions, dependent: :destroy
  has_many :comments, dependent: :destroy

  def first_name
    self.name.split.first 
  end

  def last_name
    self.name.split.last 
  end
end

app/models/user_form.rb
class UserForm < ApplicationRecord
  belongs_to :user
  has_many :form_images
  has_many :vaccs

  accepts_nested_attributes_for :vaccs,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['rec'].blank? }

  accepts_nested_attributes_for :form_images,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['main_image'].blank? }
end

app/models/vacc.rb
class Vacc < ApplicationRecord
  belongs_to :user_form

  validates_presence_of :title
end

app/models/vaccination.rb
class Vaccination < ApplicationRecord
  validates_presence_of :title
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :set_discussion, only: [:show, :edit, :update, :destroy]
  access all: [:index, :show, :new, :edit, :create, :update, :destroy], user: :all

  # GET /discussions
  def index
    @discussions = Discussion.all
  end

  # GET /discussions/1
  def show
    @discussion = Discussion.includes(:comments).find(params[:id])
    @comment = Comment.new
  end

  # GET /discussions/new
  def new
    @discussion = Discussion.new
  end

  # GET /discussions/1/edit
  def edit
  end

  # POST /discussions
  def create
    @discussion = Discussion.new(discussion_params)
    @discussion.user_id = current_user.id 

    if @discussion.save
      redirect_to @discussion, notice: 'Discussion was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /discussions/1
  def update
    if @discussion.update(discussion_params)
      redirect_to @discussion, notice: 'Discussion was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /discussions/1
  def destroy
    @discussion.destroy
    redirect_to discussions_url, notice: 'Discussion was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discussion
      @discussion = Discussion.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def discussion_params
      params.require(:discussion).permit(:title, :body, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def index
  end

  def tictac

  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
  def gravatar_helper user
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 50
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/user_forms_helper.rb
module UserFormsHelper
  def image_generator(height:, width:)
    "http://via.placeholder.com/#{height}x#{width}"
  end

  def form_img img, type
    if img.model.main_image? 
      img
    elsif type == 'main'
      image_generator(height: '600', width: '400')
    end
  end
end

app/helpers/vaccinations_helper.rb
module VaccinationsHelper
end

app/views/discussions/_form.html.erb
<div class="row mid-marg">
  <div class="col-md-8">
    <%= form_with(model: discussion, local: true) do |form| %>
      <% if discussion.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(discussion.errors.count, "error") %> prohibited this discussion from being saved:</h2>

          <ul>
          <% discussion.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, id: :discussion_title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, id: :discussion_body, rows: 8, class: 'form-control' %>
      </div>

      <div class="form-group large-marg">
        <%= form.submit 'Save Post', class: 'btn btn-outline-secondary btn-block' %>
      </div>
    <% end %>
  </div>
</div>

app/views/discussions/edit.html.erb
<div class="container large-marg">
  <h1>Edit Discussion</h1>

  <%= render 'form', discussion: @discussion %>

  <div class="mid-marg">
    <%= link_to 'Show', @discussion, class: 'btn' %> |
    <%= link_to 'Back', discussions_path, class: 'btn' %>
  </div>
</div>

app/views/discussions/index.html.erb
<div class="container large-marg">

  <h1 class="mid-marg">Discussions</h1>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th colspan="3"></th>
        <th>Created</th>
        <th>By</th>
      </tr>
    </thead>

    <tbody>
      <% @discussions.each do |discussion| %>
        <tr>
          <td><%= link_to discussion.title, discussion, class: 'btn' %></td>
          <td colspan="3"></td>
          <td><%= distance_of_time_in_words(discussion.created_at, Time.now) %> ago</td>
          <td><%= discussion.user.first_name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <div class="large-marg col-4">
    <%= link_to 'New Discussion', new_discussion_path, class: 'btn btn-outline-primary btn-block' %>
  </div>
</div>

app/views/discussions/new.html.erb
<div class="container large-marg">
  <h1>New Discussion</h1>

  <%= render 'form', discussion: @discussion %>

  <div class="mid-marg">
    <%= link_to 'Back', discussions_path, class: 'btn' %>
  </div>
</div>

app/views/discussions/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="mid-marg">
        <div class='row'>
          <div class="col-md-4">
            <div class="marg">
              <h3><%= @discussion.title %></h3>
            </div>
            <small>Created <%= distance_of_time_in_words(@discussion.created_at, Time.now) %> ago</small>
          </div>
          <div class="col-md-8">
            <div class="card large-padd">
              <%= @discussion.body %>
            </div>
            <div class="marg text-right">
              <small><%= @discussion.user.first_name %></small>
            </div>
          </div>
        </div>
      </div>
      <hr />
      <div class="mid-marg col-8">
        <div class="marg" id="comments" data-discussion-id="<%= @discussion.id %>">
          <%= render @discussion.comments %>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="mid-marg padd">
        <%= render 'comments/comment_form' %>
      </div>
    </div>
  </div>
  

  <div class="large-marg">
    <%= link_to 'Edit', edit_discussion_path(@discussion), class: 'btn' %> |
    <%= link_to 'Back', discussions_path, class: 'btn' %>
  </div>
</div>