config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :boards
  resources :comments
  resources :discussions
  resources :user_forms
  devise_for :users
  resources :vaccinations
  root to: 'pages#home'

  get 'pages/index'
  get 'pages/tictac'

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :discussion

  validates :content, presence: true, length: { minimum: 2, maximum: 250 }

  after_create_commit { CommentBroadcastJob.perform_later(self) }
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy

  validates_presence_of :title, :body
end

app/models/form_image.rb
class FormImage < ApplicationRecord
  belongs_to :user_form

  mount_uploader :main_image, FormImageUploader
end

app/models/guest_user.rb
class GuestUser < User 
  attr_accessor :name, :email, :first_name, :last_name, :id
end

app/models/player.rb
class Player < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :editor], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name

  has_many :user_forms, dependent: :destroy
  has_many :discussions, dependent: :destroy
  has_many :comments, dependent: :destroy

  def first_name
    self.name.split.first 
  end

  def last_name
    self.name.split.last 
  end
end

app/models/user_form.rb
class UserForm < ApplicationRecord
  belongs_to :user
  has_many :form_images
  has_many :vaccs

  accepts_nested_attributes_for :vaccs,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['rec'].blank? }

  accepts_nested_attributes_for :form_images,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['main_image'].blank? }
end

app/models/vacc.rb
class Vacc < ApplicationRecord
  belongs_to :user_form

  validates_presence_of :title
end

app/models/vaccination.rb
class Vaccination < ApplicationRecord
  validates_presence_of :title
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def index
  end

  def tictac

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
  def gravatar_helper user
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 50
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/user_forms_helper.rb
module UserFormsHelper
  def image_generator(height:, width:)
    "http://via.placeholder.com/#{height}x#{width}"
  end

  def form_img img, type
    if img.model.main_image? 
      img
    elsif type == 'main'
      image_generator(height: '600', width: '400')
    end
  end
end

app/helpers/vaccinations_helper.rb
module VaccinationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewVaccForm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container large-marg">
  <div class="row">
    <div class="col-md-8">
      <% if current_user.is_a? GuestUser %>
        <div class="text-center">
          <h2 class="large-marg">Welcome</h2>
          <div class="mid-marg">
            <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-outline-secondary btn-block marg' %>
            <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-outline-secondary btn-block marg' %>
          </div>
        </div>
      <% else %>
        <div class="text-center large-marg">
          <h2>Welcome, <%= current_user.first_name %></h2>
          <div class="mid-marg">
            <%= link_to 'Create new vaccination form', new_user_form_path, class: 'btn btn-outline-info btn-block' %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-4">

    </div>
  </div>
</div>

app/views/pages/index.html.erb
<h1>Index Page</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/tictac.html.erb
<div class="container">
  <h1>Tic Tac Toe</h1>
  <div class="row">
    <div class="col-md-6">
      <div class="larg-marg">
      </div>
    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
  <nav>
    <%= link_to 'Home', root_path, class: 'btn text-dark' %>
    <%= link_to 'Index', pages_index_path, class: 'btn text-dark' %>
    <%= link_to 'Discussions', discussions_path, class: 'btn text-dark' %>
    <%= link_to 'TicTacToe', pages_tictac_path, class: 'btn text-dark' %>
    <% if !current_user.is_a? GuestUser %>
      <%= link_to 'Forms', user_forms_path, class: 'btn text-dark' %>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn text-dark' %>
      <%= link_to 'Edit Prof', edit_user_registration_path, class: 'btn text-dark' %>
      <% if current_user.role == :admin %>
        <%= link_to 'Vaccinations', vaccinations_path, class: 'btn text-dark' %>
      <% end %>
    <% else %>
      <%= link_to 'Sign Up', new_user_registration_path, class: 'btn text-dark' %>
      <%= link_to 'Login', new_user_session_path, class: 'btn text-dark' %>
    <% end %>
  </nav>
</div>