config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :boards
  resources :comments
  resources :discussions
  resources :user_forms
  devise_for :users
  resources :vaccinations
  root to: 'pages#home'

  get 'pages/index'
  get 'pages/tictac'

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :discussion

  validates :content, presence: true, length: { minimum: 2, maximum: 250 }

  after_create_commit { CommentBroadcastJob.perform_later(self) }
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy

  validates_presence_of :title, :body
end

app/models/form_image.rb
class FormImage < ApplicationRecord
  belongs_to :user_form

  mount_uploader :main_image, FormImageUploader
end

app/models/guest_user.rb
class GuestUser < User 
  attr_accessor :name, :email, :first_name, :last_name, :id
end

app/models/player.rb
class Player < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :editor], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name

  has_many :user_forms, dependent: :destroy
  has_many :discussions, dependent: :destroy
  has_many :comments, dependent: :destroy

  def first_name
    self.name.split.first 
  end

  def last_name
    self.name.split.last 
  end
end

app/models/user_form.rb
class UserForm < ApplicationRecord
  belongs_to :user
  has_many :form_images
  has_many :vaccs

  accepts_nested_attributes_for :vaccs,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['rec'].blank? }

  accepts_nested_attributes_for :form_images,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['main_image'].blank? }
end

app/models/vacc.rb
class Vacc < ApplicationRecord
  belongs_to :user_form

  validates_presence_of :title
end

app/models/vaccination.rb
class Vaccination < ApplicationRecord
  validates_presence_of :title
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def index
  end

  def tictac

  end
end

app/controllers/user_forms_controller.rb
class UserFormsController < ApplicationController
  before_action :set_user_form, only: [:show, :edit, :update, :destroy]

  # GET /user_forms
  # GET /user_forms.json
  def index
    if current_user.role == :admin
      @user_forms = UserForm.all
    else
      @user_forms = UserForm.select { |u| u.user_id == current_user.id }
    end
  end

  # GET /user_forms/1
  # GET /user_forms/1.json
  def show
  end

  # GET /user_forms/new
  def new
    @user_form = UserForm.new
    1.times { @user_form.vaccs.build }
  end

  # GET /user_forms/1/edit
  def edit
  end

  # POST /user_forms
  # POST /user_forms.json
  def create
    @user_form = UserForm.new(user_form_params)
    @user_form.user_id = current_user.id 

    respond_to do |format|
      if @user_form.save
        format.html { redirect_to @user_form, notice: 'User form was successfully created.' }
        format.json { render :show, status: :created, location: @user_form }
      else
        format.html { render :new }
        format.json { render json: @user_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_forms/1
  # PATCH/PUT /user_forms/1.json
  def update
    respond_to do |format|
      if @user_form.update(user_form_params)
        format.html { redirect_to @user_form, notice: 'User form was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_form }
      else
        format.html { render :edit }
        format.json { render json: @user_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_forms/1
  # DELETE /user_forms/1.json
  def destroy
    @user_form.destroy
    
    respond_to do |format|
      format.html { redirect_to user_forms_url, notice: 'User form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_form
      @user_form = UserForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_form_params
      params.require(:user_form).permit(:user_id, vaccs_attributes: [:id, :title, :rec, :exp, :_destroy], form_images_attributes: [:id, :main_image, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
  def gravatar_helper user
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 50
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/user_forms_helper.rb
module UserFormsHelper
  def image_generator(height:, width:)
    "http://via.placeholder.com/#{height}x#{width}"
  end

  def form_img img, type
    if img.model.main_image? 
      img
    elsif type == 'main'
      image_generator(height: '600', width: '400')
    end
  end
end

app/helpers/vaccinations_helper.rb
module VaccinationsHelper
end

app/views/user_forms/_blank_vacc_fields.html.erb
<div class="form-group nested-fields">
  <div class="row">
    <div class="col-md-8">
      <%= f.label :vaccination %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :received %>
      <%= f.date_field :rec, class: 'form-control' %>

      <%= f.label :expiration %>
      <%= f.date_field :exp, class: 'form-control' %>
    </div>

    <div class="col-md-4">
      <%= link_to_remove_association 'Remove Vaccination', f, class: 'btn btn-outline-warning btn-sm' %>
    </div>
  </div>
</div>

app/views/user_forms/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_with(model: user_form, local: true) do |f| %>
      <% if user_form.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user_form.errors.count, "error") %> prohibited this user_form from being saved:</h2>

          <ul>
          <% user_form.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <% f.fields_for :vaccs do |v| %>
          <%= render 'vacc_fields', f: v %>
        <% end %>

        <div class="marg">
          <%= link_to_add_association 'Add Selection Field...>>', f, :vaccs, partial: 'vacc_fields', class: 'btn btn-outline-success btn-sm' %> |
          <%= link_to_add_association 'Add Write-In Field...>>', f, :vaccs, partial: 'blank_vacc_fields', class: 'btn btn-outline-success btn-sm' %>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-md-8">
            <% f.fields_for :form_images do |i| %>
              <%= render 'image_fields', f: i %>
            <% end %>

            <div class="marg">
              <%= link_to_add_association 'Add Image', f, :form_images, partial: 'image_fields', class: 'btn btn-outline-secondary btn-block' %>
            </div>
          </div>
        </div>
      </div>

      <div class="form-group large-marg">
        <%= f.submit 'Save Form', class: 'btn btn-outline-primary btn-block' %>
      </div>
    <% end %>
  </div>
</div>

app/views/user_forms/_image_fields.html.erb
<div class="form-group nested-fields">
  <div class="mid-marg">
    <%= f.label :image %>
    <%= f.file_field :main_image, class: 'form-control' %>

    <%= link_to_remove_association 'Remove Image', f, class: 'btn btn-outline-warning btn-sm' %>
  </div>
</div>

app/views/user_forms/_vacc_fields.html.erb
<div class="form-group nested-fields">
  <div class="row">
    <div class="col-md-8">
      <%= f.label :vaccination %>
      <%= f.collection_select :title, Vaccination.all, :title, :title, { :prompt => 'Select an option' }, { :multiple => false, class: 'form-control'} %>

      <%= f.label :received %>
      <%= f.date_field :rec, class: 'form-control' %>

      <%= f.label :expiration %>
      <%= f.date_field :exp, class: 'form-control' %>
    </div>

    <div class="col-md-4">
      <%= link_to_remove_association 'Remove Vaccination', f, class: 'btn btn-outline-warning btn-sm' %>
    </div>
  </div>
</div>

app/views/user_forms/edit.html.erb
<div class="container large-marg">
  <div class="mid-marg">
    <h1>Editing User Form</h1>
  </div>

  <div class="marg">
    <%= render 'form', user_form: @user_form %>
  </div>

  <div class="marge">
    <%= link_to 'Show', @user_form, class: 'btn btn-light' %> |
    <%= link_to 'Back', user_forms_path, class: 'btn btn-light' %>
  </div>
</div>

app/views/user_forms/index.html.erb
<div class="container large-marg">
  <h1 class="mid-marg">User Forms</h1>

  <div class="row">
    <div class="col-md-8">
      <% @user_forms.each do |form| %>
        <div class="row mid-marg">
          <div class="col-md-4">
            <%= link_to form.user.name, form %>
            <hr />
          </div>
          <div class="col-md-4 text-right">
            <small>Created <%= distance_of_time_in_words(form.created_at, Time.now) %> ago</small>
          </div>
        </div>
      <% end %>

      <div class="large-marg">
        <%= link_to 'New User Form', new_user_form_path, class: 'btn btn-outline-secondary btn-block' %>
      </div>
    </div>
  </div>
  <%= link_to 'Back', root_path, class: 'btn btn-outline-dark btn-sm' %>
</div>

app/views/user_forms/new.html.erb
<div class="container large-marg">
  <h1>New User Form</h1>

  <div class="mid-marg">
    <%= render 'form', user_form: @user_form %>
  </div>

  <div class="marg">
    <%= link_to 'Back', user_forms_path, class: 'btn btn-light' %>
  </div>
</div>

app/views/user_forms/show.html.erb
<div class="container large-marg">
  <div class="row">
    <div class="col-md-8">
      <% @user_form.vaccs.each do |v| %>
        <div class='card marg padd'>
          <div class="row">
            <div class="col-md-4">
              <strong>Title:</strong>
              <%= v.title %>
            </div>
            <div class="col-md-8 text-right">
              <div class="marg">
                <strong>Received:</strong>
                <%= v.rec %>
              </div>
              <div class="marg">
                <strong>Expires:</strong>
                <%= v.exp %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <% @user_form.form_images.each do |i| %>
        <div class="marg">
          <%= image_tag i.main_image %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="large-marg">
    <%= link_to 'Edit', edit_user_form_path(@user_form), class: "btn btn-outline-warning" %> |
    <%= link_to 'Back', user_forms_path, class: 'btn btn-outline-secondary' %> |
    <%= link_to 'Delete', @user_form, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-outline-danger' %>
  </div>
</div>